//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFWeb.Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDFEntities : DbContext
    {
        public PDFEntities()
            : base("name=PDFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDM_Branch> tblDM_Branch { get; set; }
        public virtual DbSet<tblDM_Group> tblDM_Group { get; set; }
        public virtual DbSet<tblDM_Type> tblDM_Type { get; set; }
        public virtual DbSet<tblDM_User> tblDM_User { get; set; }
        public virtual DbSet<tblPDF_FileData> tblPDF_FileData { get; set; }
        public virtual DbSet<tblDM_Mail> tblDM_Mail { get; set; }
        public virtual DbSet<tblDM_DanhBa> tblDM_DanhBa { get; set; }
        public virtual DbSet<tblDM_DonVi> tblDM_DonVi { get; set; }
        public virtual DbSet<tblDM_PhongBan> tblDM_PhongBan { get; set; }
    }
}
