//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFWeb.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM_DanhBa
    {
        public int ID { get; set; }
        public string DonVi { get; set; }
        public string PhongBan { get; set; }
        public string ChucDanh { get; set; }
        public string HoTen { get; set; }
        public string CoQuan { get; set; }
        public string NoiBo { get; set; }
        public string DiDong { get; set; }
    }
}
