//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFWeb.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM_Type
    {
        public string TypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
