//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFWeb.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPDF_FileData
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string TypeID { get; set; }
        public string BranchID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public string ShortContent { get; set; }
        public string GroupAccess { get; set; }
        public bool IsLock { get; set; }
        public string LockUser { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public string Idea { get; set; }
        public bool IsClose { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CLoseUser { get; set; }
    }
}
