//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmap.Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHXD_MapEntities : DbContext
    {
        public CHXD_MapEntities()
            : base("name=CHXD_MapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblData> tblDatas { get; set; }
        public DbSet<tblLogo> tblLogoes { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    }
}
