//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmap.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblData
    {
        public int ID { get; set; }
        public string CHXD { get; set; }
        public string Logo { get; set; }
        public string SummaryInfo { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
