//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gmap.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string GroupID { get; set; }
        public Nullable<bool> IsLock { get; set; }
    }
}
